
FROM pytorch/pytorch:2.2.0-cuda11.8-cudnn8-runtime

ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git curl wget ca-certificates \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt

RUN python -m pip install --upgrade pip
RUN pip install -r /app/requirements.txt

COPY . /app
ENV PYTHONPATH=/app/src

ENTRYPOINT ["python", "src/train.py"]